version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: database_mysql
    restart: always
    environment:
      MYSQL_DATABASE: "moodie_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "rootpassword"
    depends_on:
      - db

  ai_service:
    build: ./backend_ai
    container_name: team20-llm-engine
    ports:
      - "3000:3030"
    volumes:
      - example-root:/root
      - example-data:/app/models
    environment:
      - MODEL_PATH=/app/models/model_weights_64acc.pth

volumes:
  mysql_data:
  example-root:
    external: true
  example-data:
    external: true
