version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: database_mqsql
    restart: always
    environment:
      MYSQL_DATABASE: "moodie_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "rootpassword"
    depends_on:
      - db

  # --- Service ใหม่สำหรับ AI ---
  ai_service:
    build: ./backend_ai # สั่งให้สร้างบ้านจากพิมพ์เขียวในโฟลเดอร์ backend_ai
    ports:
      - "3030:3030" # แมพ Port 3030 ของ AI กับเครื่องของเรา

volumes:
  mysql_data:
